---

- name: Update Server and Install Package
  hosts: myhosts
  become: true
  tasks:
    - name: Update Server
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: latest

    - name: Install htop
      ansible.builtin.dnf:
        name: htop
        state: latest
